import type { ParseState, ParseStep } from './types';
import { SOURCE_REFS } from './sourceRefs';

export function readobjnamInit(input: string): { state: ParseState; step: ParseStep } {
  const state: ParseState = {
    input,
    origInput: input,
    fruitbuf: input,
    oclass: null,
    un: null,
    dn: null,
    actualn: null,
    name: null,
    otyp: null,
    cnt: 0,
    spe: 0,
    spesgn: 1,
    spesgnExplicit: false,
    very: false,
    rechrg: 0,
    blessed: false,
    uncursed: false,
    iscursed: false,
    ispoisoned: false,
    isgreased: false,
    eroded: 0,
    eroded2: 0,
    erodeproof: false,
    locked: false,
    unlocked: false,
    broken: false,
    open: false,
    closed: false,
    doorless: false,
    looted: false,
    real: false,
    fake: false,
    halfeaten: false,
    mntmp: null,
    mgend: null,
    contents: null,
    islit: false,
    unlabeled: false,
    ishistoric: false,
    isdiluted: false,
    trapped: 0,
    wetness: 0,
    gsize: null,
    ftype: null,
    zombify: false,
    isArtifact: false,
    artifactName: null,
  };

  const step: ParseStep = {
    id: 'init',
    stage: 'init',
    title: 'Initialize parse state',
    matched: true,
    inputBefore: input,
    inputAfter: input,
    stateDiff: {},
    sourceRef: SOURCE_REFS.readobjnamInit,
    category: 'lex',
    notes: ['Zeroes every field of the parse-state struct before parsing begins.'],
  };

  return { state, step };
}
